### PR TITLE
Fail fast when core plugins are not applied to root project

### LINKED ISSUE #671: Fail fast when plugin not applied to root project
Our core plugins
 - org.shipkit.java
 - org.shipkit.gradle-plugin

need to be applied to the root project.

This is not intuitive as evidenced by a problem reported at #655

Let's implement a short term solution and fail early and gracefully when the plugin is applied to a subproject rather than to a root project.

Example implementation we already use in a different plugin: 

https://github.com/mockito/shipkit/blob/59aad490aa3fcd0955bd972ce939f44b8d2e72e4/subprojects/shipkit/src/main/groovy/org/shipkit/internal/gradle/git/GitOriginPlugin.java#L32-L37

Long term plan is to make the plugins work in a submodule, too.

### PR DESCRIPTION
**Pull request by epeee**
fixes #671

as described in the ticket, let's check if our core plugins are applied to the root project.

### CODE REVIEW

File: subprojects/shipkit/src/main/groovy/org/shipkit/internal/gradle/util/ProjectUtil.java [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+
+import java.util.Optional;
+
+public class ProjectUtil {
+
+    public static void requireRootProject(final Project project, final Class<?> clazz) {
+        requireRootProject(project, clazz, Optional.empty());
+    }
+
+    public static void requireRootProject(final Project project, final Class<?> clazz, final Optional<String> explanation) {
```
Comment (mockitoguy) [inline subprojects/shipkit/src/main/groovy/org/shipkit/internal/gradle/util/ProjectUtil.java]: Minor: Optional is an overkill in this instance and allowing null is simpler and cleaner.

Optionals are very useful for output parameters (e.g. return types) because they force the clients to code against NPE. For input parameters, they are contrived.

File: subprojects/shipkit/src/test/groovy/org/shipkit/internal/gradle/util/ProjectUtilTest.groovy [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+        when:
+        ProjectUtil.requireRootProject(project, ProjectUtilTest)
+
+        then:
+        noExceptionThrown()
+    }
+
+    def "requireRootProject fails for non-rootProject"() {
+        def project = Mock(Project)
+        project.path >> ':subproject'
```
Comment (mockitoguy) [inline subprojects/shipkit/src/test/groovy/org/shipkit/internal/gradle/util/ProjectUtilTest.groovy]: Why is path relevant? If not, I suggest to remove it to keep the test clean!

File: subprojects/shipkit/src/test/groovy/org/shipkit/internal/gradle/util/ProjectUtilTest.groovy [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+
+        when:
+        ProjectUtil.requireRootProject(project, ProjectUtilTest)
+
+        then:
+        noExceptionThrown()
+    }
+
+    def "requireRootProject fails for non-rootProject"() {
+        def project = Mock(Project)
```
Comment (mockitoguy) [inline subprojects/shipkit/src/test/groovy/org/shipkit/internal/gradle/util/ProjectUtilTest.groovy]: Minor: I suggest to make it an initialized field to make the test cleaner and eliminate small duplication.

**Comment by epeee** [comment]
thx for your feedback!
merging...
