### PR TITLE
Fixes #315. Returning null instead of throwing exception when ghWriteToken not specified

### LINKED ISSUE #315: master branch does not build without env variables
At the moment, master branch does not build without env variables and some tests fail in IDEA. Let's fix it. It's related to @wwilk's changes so I'm assigning this ticket to him :) We can also revert temporarily to fix the build.

### PR DESCRIPTION
**Pull request by wwilk**
I can't think of a better solution for now. Maybe I'll figure it out when I'm working on https://github.com/mockito/shipkit/pull/313

### CODE REVIEW

File: src/main/groovy/org/shipkit/gradle/ReleaseConfiguration.java [hunk 1]
```diff
@@ -218,11 +222,12 @@ public String getWriteAuthToken() {
             if(envVar != null){
                 return envVar;
             }
-            throw new GradleException("Please export 'GH_WRITE_TOKEN' env variable first!\n" +
-                    "  The value of that variable is automatically used by Shipkit.\n" +
-                    "  It is highly recommended to keep write token secure and store env variable with your CI configuration.\n" +
-                    "  Alternatively, you can configure the write token explicitly:\n" +
-                    "    shipkit.gitHub.writeAuthToken = 'secret'");
+            LOG.lifecycle("  BEWARE! Shipkit.gitHub.writeAuthToken is unspecified.\n" +
```
Comment (szczepiq) [inline src/main/groovy/org/shipkit/gradle/ReleaseConfiguration.java]: Let's check this in so that the build is happy. However, we should find a better solution very soon. I suspect that now the build will show this hearty warning with every invocation for most normal builds. It gives ungraceful experience to the end users of Shipkit (we will have lots of them soon :).

**Comment by szczepiq** [comment]
I'm merging, please consider my review feedback!
