### PR TITLE
fix UpgradeDependencyPlugin for gradle 4.5.1

### LINKED ISSUE #641: UpgradeDependencyPluginIntegTest is failing while using gradle 4.5.1
It looks like one integration test is failing while using gradle 4.5.1, see
> org.shipkit.internal.gradle.versionupgrade.UpgradeDependencyPluginIntegTest > all tasks in dry run[1] FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at UpgradeDependencyPluginIntegTest.groovy:28
459 tests completed, 1 failed, 1 skipped
:shipkit:test FAILED

[gradle build scan](https://scans.gradle.com/s/baeymde7fjtz2/tests/zazkifhiktn3q-xac76iym24dlm) or [travis ci log](https://travis-ci.org/mockito/shipkit/builds/343396668#L575-L579) for details.

Additionally, after merging #639 we should get more meaningful test names.

### PR DESCRIPTION
**Pull request by epeee**
fixes #641 
and add gradle 4.5.1 to set of gradle versions used for integration testing.

### CODE REVIEW

File: subprojects/shipkit/src/test/groovy/testutil/GradleVersionsDeterminer.groovy [hunk 1]
```diff
@@ -24,7 +24,7 @@ trait GradleVersionsDeterminer {
             case null:
                 return [currentGradleVersion()]
             case QUICK_GRADLE_VERSIONS_VALUE:
-                return [currentGradleVersion(), "4.2.1", "4.0.2"].unique()
+                return [currentGradleVersion(), "4.5.1", "4.2.1", "4.0.2"].unique()
```
Comment (szpak) [inline subprojects/shipkit/src/test/groovy/testutil/GradleVersionsDeterminer.groovy]: Thanks for applying my comment from the previous PR review ;).

**Comment by mockitoguy** [comment]
Curious: why does the order matter / how does this particular change fix the issue?
