### PR TITLE
Windows test fixes

### LINKED ISSUE #616: Unit tests that use exec fail on Windows
Due to the nature of the `exec` system on Windows, tests that use `exec` fail because they cannot find the `echo` executable (because it's part of `cmd.exe`). As a stop-gap measure before a Windows workaround, we could disable/ignore the failing tests when run on Windows.

### PR DESCRIPTION
**Pull request by magneticflux-**
Closes #616 

Also fixes some other small Windows-specific unit test issues.

### CODE REVIEW

File: subprojects/shipkit/src/main/groovy/org/shipkit/internal/gradle/notes/tasks/UpdateReleaseNotes.java [hunk 1]
```diff
@@ -108,6 +108,6 @@ private String getVcsCommitTemplate(UpdateReleaseNotesTask task) {
     }
 
     public String getReleaseNotesUrl(UpdateReleaseNotesTask task, String branch) {
-        return  task.getGitHubUrl() + "/" + task.getGitHubRepository() + "/blob/" + branch + "/" + task.getProject().relativePath(task.getReleaseNotesFile());
+        return task.getGitHubUrl() + "/" + task.getGitHubRepository() + "/blob/" + branch + "/" + task.getProject().relativePath(task.getReleaseNotesFile()).replace('\\', '/');
```
Comment (mockitoguy) [inline subprojects/shipkit/src/main/groovy/org/shipkit/internal/gradle/notes/tasks/UpdateReleaseNotes.java]: Cool! Do you mind extracting a utility method to some other class, for getting the relative path safely. For example:

```Java
String relativePath(Project project, File file)
```

File: subprojects/shipkit/src/test/groovy/org/shipkit/gradle/exec/ShipkitExecTaskTest.groovy [hunk 2]
```diff
@@ -3,10 +3,13 @@ package org.shipkit.gradle.exec
 import org.gradle.api.tasks.TaskExecutionException
 import org.gradle.testfixtures.ProjectBuilder
 import org.shipkit.internal.gradle.exec.ExecCommandFactory
+import spock.lang.IgnoreIf
 import spock.lang.Specification
+import spock.util.environment.OperatingSystem
 
 import static org.shipkit.internal.gradle.exec.ExecCommandFactory.execCommand
 
+@IgnoreIf({ OperatingSystem.current.isWindows() })
```
Comment (mockitoguy) [inline subprojects/shipkit/src/test/groovy/org/shipkit/gradle/exec/ShipkitExecTaskTest.groovy]: Smart! Spock is a cool framework, isn't it? :)

File: subprojects/shipkit/src/main/groovy/org/shipkit/internal/gradle/plugin/tasks/PluginValidator.java [hunk 3]
```diff
@@ -84,7 +84,7 @@ private static String processPart(String pluginIdPart) {
     }
 
     private boolean ensureImplementationClassExists(String implementationClass) {
-        String pathToClass = implementationClass.replaceAll("\\.", File.separator);
+        String pathToClass = implementationClass.replace('.', File.separatorChar);
```
Comment (mockitoguy) [inline subprojects/shipkit/src/main/groovy/org/shipkit/internal/gradle/plugin/tasks/PluginValidator.java]: Nice and simple!
