### PR TITLE
Fixes problem with automatic merges

### LINKED ISSUE #646: Automatically merging pr's is failing while calling github rest api
It looks like the problem is the head we are using (it should rather be upgrade-shipkit-to-2.0.2):

> [upgradeDownstream] [performVersionUpgrade] All checks passed! Merging pull request in repository 'mockito/shipkit' between base = 'master' and head = 'mockito:upgrade-shipkit-to-2.0.2'.
> ...
> [upgradeDownstream] [performVersionUpgrade] Execution failed for task ':mergePullRequest'.
> [upgradeDownstream] [performVersionUpgrade] > Exception happen while trying to merge pull request. Merge aborted. Original issue: POST https://api.github.com/repos/mockito/shipkit/merges failed, response code = 404, response body:
> [upgradeDownstream] [performVersionUpgrade]   {"message":"Head does not exist","documentation_url":"https://developer.github.com/v3/repos/merging/#perform-a-merge"}

see [build scan](https://scans.gradle.com/s/c2zpvxr3cgiwy) for details.

### PR DESCRIPTION
**Pull request by epeee**
fixes #646

### CODE REVIEW

**Comment by epeee** [comment]
I just merged https://github.com/mockito/shipkit-example/pull/170 using the rest api also used in this pr and it did work :smile:

File: subprojects/shipkit/src/main/groovy/org/shipkit/internal/gradle/versionupgrade/MergePullRequest.java [hunk 1]
```diff
@@ -50,7 +50,7 @@ public void mergePullRequest(MergePullRequestTask task, GitHubApi gitHubApi, Git
             }
 
             LOG.lifecycle("All checks passed! Merging pull request in repository '{}' between base = '{}' and head = '{}'.", task.getUpstreamRepositoryName(), task.getBaseBranch(), headBranch);
-            gitHubApi.post("/repos/" + task.getUpstreamRepositoryName() + "/merges", body);
+            gitHubApi.post("/repos/" + task.getUpstreamRepositoryName() + "/pulls/" + task.getPullRequestNumber() + "/merge", body);
```
Comment (mockitoguy) [inline subprojects/shipkit/src/main/groovy/org/shipkit/internal/gradle/versionupgrade/MergePullRequest.java]: This is a nice change. Thank you!

File: subprojects/shipkit/src/test/groovy/org/shipkit/internal/gradle/util/BranchUtilsTest.groovy [hunk 2]
```diff
@@ -0,0 +1,17 @@
+package org.shipkit.internal.gradle.util
+
+import spock.lang.Specification
+
+class BranchUtilsTest extends Specification {
```
Comment (mockitoguy) [inline subprojects/shipkit/src/test/groovy/org/shipkit/internal/gradle/util/BranchUtilsTest.groovy]: Cool! Thank you for adding missing test.

**Comment by mockitoguy** [comment]
Merging. Nice change!
