### PR TITLE
Fix GitHub release notes encoding

### LINKED ISSUE #813: Github release notes encoding
During Shipkit workshops with @mstachniuk we discovered that there is wrong encoding in github release notes published by shipkit: https://github.com/krzemin/shipkit-workshop-15/releases/tag/v1.0.1, while `docs/release-notes.md` file encoding is fine https://github.com/krzemin/shipkit-workshop-15/blob/master/docs/release-notes.md

Is it shipkit to blame?

### PR DESCRIPTION
**Pull request by mstachniuk**
Fix #813

### CODE REVIEW

File: subprojects/shipkit/src/main/groovy/org/shipkit/internal/util/GitHubApi.java [hunk 1]
```diff
@@ -56,10 +57,9 @@ private String doRequest(String relativeUrl, String method, Optional<String> bod
         conn.setRequestProperty("Authorization", "token " + authToken);
 
         if (body.isPresent()) {
-            try (DataOutputStream wr = new DataOutputStream(conn.getOutputStream())) {
-                wr.writeBytes(body.get());
-                wr.flush();
-            }
+            OutputStream os = conn.getOutputStream();
+            os.write(body.get().getBytes(Charset.forName("UTF-8")));
```
Comment (epeee) [inline subprojects/shipkit/src/main/groovy/org/shipkit/internal/util/GitHubApi.java]: let's use `StandardCharsets.UTF_8` here

File: subprojects/shipkit/src/main/groovy/org/shipkit/internal/util/GitHubApi.java [hunk 2]
```diff
@@ -56,10 +57,9 @@ private String doRequest(String relativeUrl, String method, Optional<String> bod
         conn.setRequestProperty("Authorization", "token " + authToken);
 
         if (body.isPresent()) {
-            try (DataOutputStream wr = new DataOutputStream(conn.getOutputStream())) {
-                wr.writeBytes(body.get());
-                wr.flush();
-            }
+            OutputStream os = conn.getOutputStream();
```
Comment (epeee) [inline subprojects/shipkit/src/main/groovy/org/shipkit/internal/util/GitHubApi.java]: Let's re-add the try-with-resources here

File: subprojects/shipkit/src/main/groovy/org/shipkit/internal/util/GitHubApi.java [hunk 3]
```diff
@@ -78,3 +78,5 @@ private String call(String method, HttpsURLConnection conn) throws IOException {
         }
     }
 }
+//https://api.github.com/repos/mstachniuk/mockito/releases
```
Comment (epeee) [inline subprojects/shipkit/src/main/groovy/org/shipkit/internal/util/GitHubApi.java]: let's also remove this comment or add it as a more general one to the doc if needed
