### PR TITLE
fix gradle badge generation

### LINKED ISSUE #774: Fix Badge generation for Gradle Plugin Portal in Release Notes
The badge where Shipkit is published is wrong generated:
https://github.com/mockito/shipkit/blob/master/docs/release-notes.md

zrzut ekranu 2019-02-20 o 02 39 02

The generated badge (after adding `releaseNotes.publicationPluginName = "org.shipkit.java.gradle.plugin"` in shipkit.gradle), generate always the badge with the newest version, but it should be fixed version. The `releaseNotes.publicationPluginName` should be probably deprecated and remove in the future.

The bug was introduced by: https://github.com/mockito/shipkit/pull/750

### PR DESCRIPTION
**Pull request by epeee**
fixes #774 

now generates badges like Gradle

I've already adjusted the badges of the last two releases in docs/release-notes.md

### CODE REVIEW

**Comment by epeee** [comment]
let's merge #783 first

File: subprojects/shipkit/src/main/groovy/org/shipkit/internal/notes/format/BadgeFormatter.java [hunk 1]
```diff
@@ -17,11 +17,8 @@ public String getRepositoryBadge(String version, String publicationRepository, S
     }
 
     private String gradlePluginPortalBadge(String version, String publicationRepository, String pluginName) {
```
Comment (mstachniuk) [inline subprojects/shipkit/src/main/groovy/org/shipkit/internal/notes/format/BadgeFormatter.java]: Now `pluginName` is unused. So you can remove all usages and mark: 
- `get/setPublicationPluginName` in `AbstractReleaseNotesTask`
- `get/setPublicationPluginName` in `ReleaseNotes`
as deprecated.
I would remove it in the next MAJOR version.
Don't forget to bump the minor version of Shipkit to follow SemVer!
I'm working on https://github.com/mockito/shipkit/issues/233 (it should be ready to review in 2 weeks), so we can merge this PR + my together (to bump minor only once and add new value for users).

File: docs/release-notes.md [hunk 2]
```diff
@@ -1,13 +1,13 @@
...
  - Make sure that gitPush is executed before updateReleaseNotesOnGithub [(#782)](https://github.com/mockito/shipkit/pull/782)
  - Update objenesis (v3.0.1) and get rid of not needed dependency [(#780)](https://github.com/mockito/shipkit/pull/780)
  - Version of shipkit upgraded to 2.1.3 [(#779)](https://github.com/mockito/shipkit/pull/779)
 
 #### 2.1.3
- - 2019-02-23 - [2 commits](https://github.com/mockito/shipkit/compare/v2.1.2...v2.1.3) by [Marcin Stachniuk](https://github.com/mstachniuk) - published to [![Gradle](https://img.shields.io/maven-metadata/v/https/plugins.gradle.org/m2/org/shipkit/java/maven-metadata.xml.svg?colorB=007ec6&label=Gradle)](https://plugins.gradle.org/plugin/org.shipkit.java/2.1.3)
+ - 2019-02-23 - [2 commits](https://github.com/mockito/shipkit/compare/v2.1.2...v2.1.3) by [Marcin Stachniuk](https://github.com/mstachniuk) - published to [![Gradle](https://img.shields.io/badge/Gradle-v2.1.3-blue.svg)](https://plugins.gradle.org/plugin/org.shipkit.java/2.1.3)
```
Comment (mstachniuk) [inline docs/release-notes.md]: Minor. It would be nice to fix all badges for all versions. Btw. 2.1.4, 2.1.2, 2.1.1 didn't exist - error during deployment.

File: subprojects/shipkit/src/main/groovy/org/shipkit/internal/notes/format/BadgeFormatter.java (hunk 1 above)
Comment (mstachniuk) [reply subprojects/shipkit/src/main/groovy/org/shipkit/internal/notes/format/BadgeFormatter.java]: Ok, now I see `ReleaseNotes` are fixed in https://github.com/mockito/shipkit/pull/785 but still more code should be removed in this PR.

File: docs/release-notes.md (hunk 2 above)
Comment (epeee) [reply docs/release-notes.md]: thx, yes, I will do so.

File: subprojects/shipkit/src/main/groovy/org/shipkit/internal/notes/format/BadgeFormatter.java (hunk 1 above)
Comment (epeee) [reply subprojects/shipkit/src/main/groovy/org/shipkit/internal/notes/format/BadgeFormatter.java]: thank you, I will revisit the code and will remove not needed code.
